/*
 * 파일명: OptionsData.cs
 * 분류: [Data] 설정 화면 텍스트
 * 역할: 게임 설정(Options) 화면의 카테고리 및 설정 항목 텍스트를 정의합니다.
 */

using System.Collections.Generic;

namespace QudKRTranslation.Data
{
    public static class OptionsData
    {
        public static Dictionary<string, string> Translations = new Dictionary<string, string>()
        {
            { ".5", "" },
            { ".75", "" },
            { "0", "" },
            { "1", "" },
            { "1.0", "" },
            { "1.25", "" },
            { "1.5", "" },
            { "10", "" },
            { "100%", "" },
            { "120", "" },
            { "15", "" },
            { "2", "" },
            { "20", "" },
            { "20%", "" },
            { "3", "" },
            { "30", "" },
            { "4", "" },
            { "40", "" },
            { "40%", "" },
            { "5", "" },
            { "50", "" },
            { "6", "" },
            { "60", "" },
            { "60%", "" },
            { "7", "" },
            { "8", "" },
            { "80%", "" },
            { "<color=#77BFCFFF>ABILITY BAR MODE</color>", "" },
            { "<color=#77BFCFFF>ADD A LINE SEPARATOR AT THE END OF EACH ROUND DURING COMBAT</color>", "" },
            { "<color=#77BFCFFF>ALLOW CREATURES TO HAVE MULTIPLE DEFECTS </color>", "" },
            { "<color=#77BFCFFF>ALLOW MOUSE INPUT</color>", "" },
            { "<color=#77BFCFFF>ALLOW MOUSE MOVEMENT</color>", "" },
            { "<color=#77BFCFFF>ALLOW SCRIPTING MODS (SCRIPTING MODS MAY CONTAIN MALICIOUS CODE!)</color>", "" },
            { "<color=#77BFCFFF>ALLOW SCROLL WHEEL TO ZOOM</color>", "" },
            { "<color=#77BFCFFF>ALWAYS HIGHLIGHT STAIRS</color>", "" },
            { "<color=#77BFCFFF>ALWAYS MAP DIRECTIONS TO NUMPAD</color>", "" },
            { "<color=#77BFCFFF>ALWAYS PASS A-Z HOTKEYS THROUGH TO THE LEGACY UI</color>", "" },
            { "<color=#77BFCFFF>AMBIENT SOUNDS</color>", "" },
            { "<color=#77BFCFFF>AMBIENT VOLUME</color>", "" },
            { "<color=#77BFCFFF>ATTACK IGNORED HOSTILES THAT YOU MOVE ADJACENT TO DURING AUTOEXPLORE</color>", "" },
            { "<color=#77BFCFFF>AUTOGET AMMO</color>", "" },
            { "<color=#77BFCFFF>AUTOGET ARTIFACTS</color>", "" },
            { "<color=#77BFCFFF>AUTOGET BOOKS</color>", "" },
            { "<color=#77BFCFFF>AUTOGET COPPER, SILVER, AND GOLD NUGGETS</color>", "" },
            { "<color=#77BFCFFF>AUTOGET FOOD</color>", "" },
            { "<color=#77BFCFFF>AUTOGET FRESH WATER</color>", "" },
            { "<color=#77BFCFFF>AUTOGET FROM ADJACENT CELLS</color>", "" },
            { "<color=#77BFCFFF>AUTOGET IF HOSTILES ARE NEARBY</color>", "" },
            { "<color=#77BFCFFF>AUTOGET LIQUIDS FROM CONTAINERS YOU'VE DROPPED</color>", "" },
            { "<color=#77BFCFFF>AUTOGET PRIMITIVE AMMO</color>", "" },
            { "<color=#77BFCFFF>AUTOGET SCRAP</color>", "" },
            { "<color=#77BFCFFF>AUTOGET SPECIAL ITEMS</color>", "" },
            { "<color=#77BFCFFF>AUTOGET TRADE GOODS</color>", "" },
            { "<color=#77BFCFFF>AUTOGET WEIGHTLESS ITEMS</color>", "" },
            { "<color=#77BFCFFF>AUTOMATICALLY DIG THROUGH WALLS BY MOVING INTO THEM WHEN WIELDING A DIGGING IMPLEMENT</color>", "" },
            { "<color=#77BFCFFF>AUTOMATICALLY DISASSEMBLE SCRAP</color>", "" },
            { "<color=#77BFCFFF>AUTOMATICALLY DOUSE AND LIGHT TORCHES</color>", "" },
            { "<color=#77BFCFFF>AUTOMATICALLY DRINK FRESH WATER WHEN THIRSTY</color>", "" },
            { "<color=#77BFCFFF>AUTOMATICALLY HIDE MOUSE CURSOR WHEN INACTIVE</color>", "" },
            { "<color=#77BFCFFF>AUTOMATICALLY SAVE WHEN MOVING TO A DIFFERENT ZONE</color>", "" },
            { "<color=#77BFCFFF>BRIGHTNESS</color>", "" },
            { "<color=#77BFCFFF>CHARACTER SHEET SCALE PERCENTAGE</color>", "" },
            { "<color=#77BFCFFF>CHARACTER SHEET SIZE</color>", "" },
            { "<color=#77BFCFFF>CHECK MEMORY USAGE AND SHOW A WARNING WHEN IT'S HIGH</color>", "" },
            { "<color=#77BFCFFF>COLOR HIT HEARTS PER THE TARGET'S REMAINING HP</color>", "" },
            { "<color=#77BFCFFF>COLOR YOUR CHARACTER'S GLYPH BASED ON HEALTH STATUS</color>", "" },
            { "<color=#77BFCFFF>COMBAT SOUNDS</color>", "" },
            { "<color=#77BFCFFF>COMBAT VOLUME</color>", "" },
            { "<color=#77BFCFFF>CONTRAST</color>", "" },
            { "<color=#77BFCFFF>CONTROL MAPPING</color>", "" },
            { "<color=#77BFCFFF>DEFAULT THE SELECTION ON DEATH PROMPTS IN ROLEPLAY MODE TO 'VIEW FINAL MESSAGES' INSTEAD OF 'RELOAD CHECKPOINT'</color>", "" },
            { "<color=#77BFCFFF>DIFFICULTY THRESHOLD FOR IGNORING HOSTILE CREATURES</color>", "" },
            { "<color=#77BFCFFF>DISABLE ACHIEVEMENTS</color>", "" },
            { "<color=#77BFCFFF>DISABLE BLOOD SPLATTERS</color>", "" },
            { "<color=#77BFCFFF>DISABLE BRAIN HIJACKING ON PLAYER-CONTROLLED CHARACTERS</color>", "" },
            { "<color=#77BFCFFF>DISABLE CONFLICT CHECKING WHEN REBINDING CONTROLS</color>", "" },
            { "<color=#77BFCFFF>DISABLE FLOOR TEXTURES</color>", "" },
            { "<color=#77BFCFFF>DISABLE FULLSCREEN SCREEN-WARPING EFFECTS</color>", "" },
            { "<color=#77BFCFFF>DISABLE INPUT WARNING</color>", "" },
            { "<color=#77BFCFFF>DISABLE LIMIT ON ZONE BUILD TRIES</color>", "" },
            { "<color=#77BFCFFF>DISABLE MODERN, TILE-BASED GRAPHICAL EFFECTS</color>", "" },
            { "<color=#77BFCFFF>DISABLE MOST TILE-BASED FLASHING EFFECTS</color>", "" },
            { "<color=#77BFCFFF>DISABLE PRELOADING OF SOUNDS</color>", "" },
            { "<color=#77BFCFFF>DISABLE SMOKE EFFECTS</color>", "" },
            { "<color=#77BFCFFF>DISABLE TILE-BASED SCREEN-WARPING EFFECTS</color>", "" },
            { "<color=#77BFCFFF>DISABLE ZONE CACHING</color>", "" },
            { "<color=#77BFCFFF>DISPLAY ABILITY ICONS ON THE SIDEBAR</color>", "" },
            { "<color=#77BFCFFF>DISPLAY ASCII VISUAL EFFECTS</color>", "" },
            { "<color=#77BFCFFF>DISPLAY COMBAT ANIMATIONS</color>", "" },
            { "<color=#77BFCFFF>DISPLAY CONTENTS OF CURRENT CELL IN A POPUP</color>", "" },
            { "<color=#77BFCFFF>DISPLAY DETAILED WEAPON PENETRATION AND DAMAGE IN WEAPON NAMES</color>", "" },
            { "<color=#77BFCFFF>DISPLAY FLOATING DAMAGE NUMBERS</color>", "" },
            { "<color=#77BFCFFF>DISPLAY LOCATION INSTEAD OF NAME ON THE SIDEBAR</color>", "" },
            { "<color=#77BFCFFF>DISPLAY MODERN VISUAL EFFECTS</color>", "" },
            { "<color=#77BFCFFF>DISPLAY MOUSE-CLICKABLE ZONE TRANSITION ARROWS</color>", "" },
            { "<color=#77BFCFFF>DISPLAY OVERLAY KEYBOARD FOR INPUT ON SUPPORTED DEVICES</color>", "" },
            { "<color=#77BFCFFF>DISPLAY POPUPS WHEN NOTING INFORMATION IN YOUR JOURNAL</color>", "" },
            { "<color=#77BFCFFF>DISPLAY SCANLINES</color>", "" },
            { "<color=#77BFCFFF>DISPLAY VERBOSE LEVEL UP MESSAGES FOR COMPANIONS</color>", "" },
            { "<color=#77BFCFFF>DISPLAY VIGNETTE EFFECT</color>", "" },
            { "<color=#77BFCFFF>DO NOT GENERATE FLOOR TEXTURE OBJECTS</color>", "" },
            { "<color=#77BFCFFF>DOCK BACKGROUND OPACITY</color>", "" },
            { "<color=#77BFCFFF>DOCK MESSAGE LOG && MINIMAP</color>", "" },
            { "<color=#77BFCFFF>DON'T DELETE CLASSIC MODE SAVED GAMES ON DEATH</color>", "" },
            { "<color=#77BFCFFF>DRAW AUDIBILITY FLOOD FILL</color>", "" },
            { "<color=#77BFCFFF>DRAW CELLULAR AUTOMATA WHEN USED IN MAP GENERATION</color>", "" },
            { "<color=#77BFCFFF>DRAW CREATURE PATHFINDING </color>", "" },
            { "<color=#77BFCFFF>DRAW ELECTRICAL ARC HISTORY FOR LAST FEW ROUNDS</color>", "" },
            { "<color=#77BFCFFF>DRAW NAVIGATION WEIGHT MAPS ON EACH STEP</color>", "" },
            { "<color=#77BFCFFF>DRAW OLFACTION FLOOD FILL</color>", "" },
            { "<color=#77BFCFFF>DRAW POPULATION PLACEMENT HINT MAPS WHEN BUILDING ZONES</color>", "" },
            { "<color=#77BFCFFF>DRAW POPULATION PLACEMENT REGIONS WHEN BUILDING ZONES</color>", "" },
            { "<color=#77BFCFFF>DRAW REACHABILITY MAPS ON ZONE GENERATION</color>", "" },
            { "<color=#77BFCFFF>DRAW SEMANTIC TAG INFO WHEN BUILDING ZONES</color>", "" },
            { "<color=#77BFCFFF>DRAW VISIBILITY FLOOD FILL</color>", "" },
            { "<color=#77BFCFFF>ENABLE A 'DROP ALL' INTERACTION ON ITEMS IN YOUR INVENTORY</color>", "" },
            { "<color=#77BFCFFF>ENABLE HARMONY DEBUG OUTPUT</color>", "" },
            { "<color=#77BFCFFF>ENABLE MODERN UI CHARACTER SHEET</color>", "" },
            { "<color=#77BFCFFF>ENABLE MODERN UI</color>", "" },
            { "<color=#77BFCFFF>ENABLE MODS</color>", "" },
            { "<color=#77BFCFFF>ENABLE SAVE AND LOAD</color>", "" },
            { "<color=#77BFCFFF>ENABLE TILE GRAPHICS</color>", "" },
            { "<color=#77BFCFFF>ENABLE UNFINISHED AND UNSUPPORTED CONTENT</color>", "" },
            { "<color=#77BFCFFF>ENABLE WORKAROUND FOR STEAM DECK SHIFT KEY BUG</color>", "" },
            { "<color=#77BFCFFF>EQUIP/UNEQUIP HIGHLIGHTED ITEM WHEN PRESSING RIGHT OR LEFT, RESPECTIVELY, ON THE EQUIPMENT SCREEN</color>", "" },
            { "<color=#77BFCFFF>EXPAND THE EQUIPMENT OR INVENTORY PANE WHEN FOCUSED</color>", "" },
            { "<color=#77BFCFFF>FIRE CRACKLING SOUNDS</color>", "" },
            { "<color=#77BFCFFF>FLUSH ZONES TO CACHE EARLY (FOR LOW MEMORY ENVIRONMENTS)</color>", "" },
            { "<color=#77BFCFFF>FRAME RATE</color>", "" },
            { "<color=#77BFCFFF>FULLSCREEN RESOLUTION</color>", "" },
            { "<color=#77BFCFFF>FULLSCREEN</color>", "" },
            { "<color=#77BFCFFF>GAMEPAD BUTTON APPEARANCE</color>", "" },
            { "<color=#77BFCFFF>GARBAGE COLLECT AFTER EACH ZONE FLUSH (FOR LOW MEMORY ENVIRONMENTS)</color>", "" },
            { "<color=#77BFCFFF>GET PROMPTED TO CONFIRM DEATHS</color>", "" },
            { "<color=#77BFCFFF>INDENT BODY PARTS BY ATTACHMENT ON THE EQUIPMENT SCREEN</color>", "" },
            { "<color=#77BFCFFF>INDICATE BIOMES ON THE WORLDMAP</color>", "" },
            { "<color=#77BFCFFF>INDICATE SPECIAL ENCOUNTERS ON THE WORLDMAP</color>", "" },
            { "<color=#77BFCFFF>INTERFACE SOUNDS</color>", "" },
            { "<color=#77BFCFFF>INTERFACE VOLUME</color>", "" },
            { "<color=#77BFCFFF>INTERRUPT HELD MOVEMENT WHEN ENTERING AN UNEXPLORED ZONE</color>", "" },
            { "<color=#77BFCFFF>INTERRUPT HELD MOVEMENT WHEN HOSTILES ARE NEARBY</color>", "" },
            { "<color=#77BFCFFF>KEEP CAVES OF QUD ACTIVE IN BACKGROUND</color>", "" },
            { "<color=#77BFCFFF>KEY REPEAT DELAY</color>", "" },
            { "<color=#77BFCFFF>KEY REPEAT RATE</color>", "" },
            { "<color=#77BFCFFF>LIMIT THE INPUT BUFFER TO TWO COMMANDS</color>", "" },
            { "<color=#77BFCFFF>MAIN MENU BACKGROUND ART</color>", "" },
            { "<color=#77BFCFFF>MAIN VOLUME</color>", "" },
            { "<color=#77BFCFFF>MAP SHIFT+DIRECTIONS TO MENU PAGINATION BINDS (DOESN'T WORK FOR NUMPAD BINDINGS)</color>", "" },
            { "<color=#77BFCFFF>MAXIMUM AUTOMOVE CELLS/SEC AND AUTOATTACK ACTIONS/SEC</color>", "" },
            { "<color=#77BFCFFF>MESSAGE LOG FONT SIZE (PT)</color>", "" },
            { "<color=#77BFCFFF>MOUSE CURSOR APPEARANCE</color>", "" },
            { "<color=#77BFCFFF>MOVE TUTORIAL TO THE END OF THE GAME MODE LIST</color>", "" },
            { "<color=#77BFCFFF>MUSIC VOLUME</color>", "" },
            { "<color=#77BFCFFF>MUSIC</color>", "" },
            { "<color=#77BFCFFF>NAVIGATE INVENTORY AND EQUIPMENT PANES WITH LEFT/RIGHT PAGINATION INSTEAD OF MOVEMENT BINDS</color>", "" },
            { "<color=#77BFCFFF>NEARBY OBJECTS LIST: SHOW LIQUID POOLS</color>", "" },
            { "<color=#77BFCFFF>NEARBY OBJECTS LIST: SHOW ONLY CURRENT CELL'S CONTENTS</color>", "" },
            { "<color=#77BFCFFF>NEARBY OBJECTS LIST: SHOW ONLY SHOW TAKEABLE OBJECTS</color>", "" },
            { "<color=#77BFCFFF>NEARBY OBJECTS LIST: SHOW PLANTS</color>", "" },
            { "<color=#77BFCFFF>NUMBER OF ROLLING BACKUP SAVES</color>", "" },
            { "<color=#77BFCFFF>PERFORM INVENTORY CONSISTENCY CHECKS</color>", "" },
            { "<color=#77BFCFFF>PIXEL PERFECT TILE GRAPHIC SCALE</color>", "" },
            { "<color=#77BFCFFF>PLAY AREA SCALE</color>", "" },
            { "<color=#77BFCFFF>PREGENERATE ZONE NAMES FOR WISH SUPPORT</color>", "" },
            { "<color=#77BFCFFF>PRESSING SHIFT HIDES THE SIDEBAR</color>", "" },
            { "<color=#77BFCFFF>PROMPT BEFORE AUTOWALKING TO STAIRS</color>", "" },
            { "<color=#77BFCFFF>PROMPT BEFORE DRINKING AND MOVING INTO CERTAIN DANGEROUS LIQUIDS</color>", "" },
            { "<color=#77BFCFFF>PROMPT BEFORE MOVING TO THE WORLD MAP</color>", "" },
            { "<color=#77BFCFFF>PROMPT BEFORE SWIMMING</color>", "" },
            { "<color=#77BFCFFF>PROMPT LIST OF ITEMS WHEN GETTING FROM THE GROUND, EVEN IF THERE'S ONLY ONE</color>", "" },
            { "<color=#77BFCFFF>RANGE THRESHOLD FOR IGNORING HOSTILE CREATURES</color>", "" },
            { "<color=#77BFCFFF>SEARCH CONTAINERS WHILE AUTOEXPLORING</color>", "" },
            { "<color=#77BFCFFF>SEND ANONYMOUS GAMEPLAY STATISTICS</color>", "" },
            { "<color=#77BFCFFF>SHOW ABILITY-ON-COOLDOWN PROMPTS AS MESSAGE LOG ENTRIES INSTEAD OF POPUPS</color>", "" },
            { "<color=#77BFCFFF>SHOW ADVANCED OPTIONS</color>", "" },
            { "<color=#77BFCFFF>SHOW ATTITUDE INFO ON OBJECTS</color>", "" },
            { "<color=#77BFCFFF>SHOW COLLECTOR'S SEALS ON THE MAIN MENU</color>", "" },
            { "<color=#77BFCFFF>SHOW DAMAGE PENETRATION DEBUG TEXT</color>", "" },
            { "<color=#77BFCFFF>SHOW DEBUG INFO ON OBJECTS</color>", "" },
            { "<color=#77BFCFFF>SHOW DEBUG TEXT FOR STAT SHIFTS</color>", "" },
            { "<color=#77BFCFFF>SHOW ENCOUNTER CHANCE DEBUG CHANCE</color>", "" },
            { "<color=#77BFCFFF>SHOW ERROR POPUPS</color>", "" },
            { "<color=#77BFCFFF>SHOW LOST CHANCE DEBUG TEXT</color>", "" },
            { "<color=#77BFCFFF>SHOW MINIMAP</color>", "" },
            { "<color=#77BFCFFF>SHOW NEARBY OBJECTS LIST</color>", "" },
            { "<color=#77BFCFFF>SHOW NUMBER OF ITEMS IN EACH INVENTORY CATEGORY</color>", "" },
            { "<color=#77BFCFFF>SHOW POPUPS WHEN YOU DISMEMBER OR DECAPITATE SOMEONE</color>", "" },
            { "<color=#77BFCFFF>SHOW QUICKSTART OPTION DURING CHARACTER CREATION</color>", "" },
            { "<color=#77BFCFFF>SHOW REPUTATION WITH A CREATURE'S FACTIONS WHEN LOOKING AT THEM</color>", "" },
            { "<color=#77BFCFFF>SHOW SAVING THROW DEBUG TEXT</color>", "" },
            { "<color=#77BFCFFF>SHOW SCAVENGED ITEMS AS MESSAGE LOG ENTRIES INSTEAD OF POPUPS</color>", "" },
            { "<color=#77BFCFFF>SHOW THE FULL ZONE ID DURING ZONE CREATION</color>", "" },
            { "<color=#77BFCFFF>SHOW TRAVEL SPEED DEBUG TEXT</color>", "" },
            { "<color=#77BFCFFF>SHOW XML CONVERSATION AND NODE NAMES DURING CONVERSATION</color>", "" },
            { "<color=#77BFCFFF>SOUND EFFECTS VOLUME</color>", "" },
            { "<color=#77BFCFFF>SOUND EFFECTS</color>", "" },
            { "<color=#77BFCFFF>TAKE CORPSES WHEN USING THE 'TAKE ALL' COMMAND</color>", "" },
            { "<color=#77BFCFFF>THIRST THRESHOLD FOR AUTOMATIC DRINKING</color>", "" },
            { "<color=#77BFCFFF>THRESHOLD FOR LOW HITPOINT WARNING</color>", "" },
            { "<color=#77BFCFFF>THROTTLE ANIMATIONS (FOR LOW CPU ENVIRONMENTS)</color>", "" },
            { "<color=#77BFCFFF>TOOLTIP DELAY (MS)</color>", "" },
            { "<color=#77BFCFFF>UI SCALE</color>", "" },
            { "<color=#77BFCFFF>USE TEXT AUTOACT INTERRUPT INDICATOR INSTEAD OF FLASHING RED BOX</color>", "" },
            { "<color=#77BFCFFF>WAIT FOR KEYPRESS WHEN DRAWING PATHFINDING</color>", "" },
            { "<color=#77BFCFFF>WHEN ZOOMED OUT TO MAX ZOOM, REMOVE THE UI FRAME FROM THE MAIN GAMEPLAY SCREEN</color>", "" },
            { "<color=#77BFCFFF>WRITE COMPILED MOD ASSEMBLIES TO DISK</color>", "" },
            { "<color=#77BFCFFF>WRITE PLAYED SOUND FILE NAMES TO MESSAGE LOG</color>", "" },
            { "<color=#77BFCFFF>ZOOM SENSITIVITY</color>", "" },
            { "ABILITY BAR MODE", "" },
            { "ADD A LINE SEPARATOR AT THE END OF EACH ROUND DURING COMBAT", "" },
            { "ALLOW CREATURES TO HAVE MULTIPLE DEFECTS ", "" },
            { "ALLOW MOUSE INPUT", "" },
            { "ALLOW MOUSE MOVEMENT", "" },
            { "ALLOW MUTATIONS TO RECOLOR YOUR CHARACTER'S GLYPH", "" },
            { "ALLOW SCRIPTING MODS (SCRIPTING MODS MAY CONTAIN MALICIOUS CODE!)", "" },
            { "ALLOW SCROLL WHEEL TO ZOOM", "" },
            { "ALWAYS HIGHLIGHT STAIRS", "" },
            { "ALWAYS MAP DIRECTIONS TO NUMPAD", "" },
            { "ALWAYS PASS A-Z HOTKEYS THROUGH TO THE LEGACY UI", "" },
            { "AMBIENT SOUNDS", "" },
            { "AMBIENT VOLUME", "" },
            { "ATTACK IGNORED HOSTILES THAT YOU MOVE ADJACENT TO DURING AUTOEXPLORE", "" },
            { "AUTOGET AMMO", "" },
            { "AUTOGET ARTIFACTS", "" },
            { "AUTOGET BOOKS", "" },
            { "AUTOGET COPPER, SILVER, AND GOLD NUGGETS", "" },
            { "AUTOGET FOOD", "" },
            { "AUTOGET FRESH WATER", "" },
            { "AUTOGET FROM ADJACENT CELLS", "" },
            { "AUTOGET IF HOSTILES ARE NEARBY", "" },
            { "AUTOGET LIQUIDS FROM CONTAINERS YOU'VE DROPPED", "" },
            { "AUTOGET PRIMITIVE AMMO", "" },
            { "AUTOGET SCRAP", "" },
            { "AUTOGET SPECIAL ITEMS", "" },
            { "AUTOGET TRADE GOODS", "" },
            { "AUTOGET WEIGHTLESS ITEMS", "" },
            { "AUTOMATICALLY DIG THROUGH WALLS BY MOVING INTO THEM WHEN WIELDING A DIGGING IMPLEMENT", "" },
            { "AUTOMATICALLY DISASSEMBLE SCRAP", "" },
            { "AUTOMATICALLY DOUSE AND LIGHT TORCHES", "" },
            { "AUTOMATICALLY DRINK FRESH WATER WHEN THIRSTY", "" },
            { "AUTOMATICALLY HIDE MOUSE CURSOR WHEN INACTIVE", "" },
            { "AUTOMATICALLY SAVE WHEN MOVING TO A DIFFERENT ZONE", "" },
            { "Ability bar mode", "" },
            { "Add a line separator at the end of each round during combat", "" },
            { "Allow creatures to have multiple defects", "" },
            { "Allow creatures to have multiple defects ", "" },
            { "Allow mouse input", "" },
            { "Allow mouse movement", "" },
            { "Allow mutations to recolor your character's glyph", "" },
            { "Allow scripting mods (scripting mods may contain malicious code!)", "" },
            { "Allow scroll wheel to zoom", "" },
            { "Alternate", "" },
            { "Always highlight stairs", "" },
            { "Always map directions to numpad", "" },
            { "Always pass A-Z hotkeys through to the legacy UI", "" },
            { "Ambient sounds", "" },
            { "Ambient volume", "" },
            { "Attack ignored hostiles that you move adjacent to during autoexplore", "" },
            { "Auto", "" },
            { "Autoget ammo", "" },
            { "Autoget artifacts", "" },
            { "Autoget books", "" },
            { "Autoget copper, silver, and gold nuggets", "" },
            { "Autoget food", "" },
            { "Autoget fresh water", "" },
            { "Autoget from adjacent cells", "" },
            { "Autoget if hostiles are nearby", "" },
            { "Autoget liquids from containers you've dropped", "" },
            { "Autoget primitive ammo", "" },
            { "Autoget scrap", "" },
            { "Autoget special items", "" },
            { "Autoget trade goods", "" },
            { "Autoget weightless items", "" },
            { "Automatically dig through walls by moving into them when wielding a digging implement", "" },
            { "Automatically disassemble scrap", "" },
            { "Automatically douse and light torches", "" },
            { "Automatically drink fresh water when thirsty", "" },
            { "Automatically hide mouse cursor when inactive", "" },
            { "Automatically save when moving to a different zone", "" },
            { "Average", "" },
            { "BRIGHTNESS", "" },
            { "Brightness", "" },
            { "CHARACTER SHEET SCALE PERCENTAGE", "" },
            { "CHARACTER SHEET SIZE", "" },
            { "CHECK MEMORY USAGE AND SHOW A WARNING WHEN IT'S HIGH", "" },
            { "COLOR HIT HEARTS PER THE TARGET'S REMAINING HP", "" },
            { "COLOR YOUR CHARACTER'S GLYPH BASED ON HEALTH STATUS", "" },
            { "COMBAT SOUNDS", "" },
            { "COMBAT VOLUME", "" },
            { "CONTRAST", "" },
            { "CONTROL MAPPING", "" },
            { "Character sheet scale percentage", "" },
            { "Character sheet size", "" },
            { "Check memory usage and show a warning when it's high", "" },
            { "Classic", "" },
            { "Color hit hearts per the target's remaining HP", "" },
            { "Color your character's glyph based on health status", "" },
            { "Combat sounds", "" },
            { "Combat volume", "" },
            { "Compact", "" },
            { "Contrast", "" },
            { "Control Mapping", "" },
            { "Controls how the play area will scale in the area not used by the UI.\n\n        {{W|Fit}}: Fits the whole play area on screen. May necessitate letterboxing.\n        {{W|Cover}}: Ensures the play area covers the screen. Minimizes letterboxing.\n        {{W|Pixel Perfect}}: Sizes the play area to an integer multiple of the pixel art. Maximizes sharpness.", "" },
            { "Cover", "" },
            { "DEFAULT THE SELECTION ON DEATH PROMPTS IN ROLEPLAY MODE TO 'VIEW FINAL MESSAGES' INSTEAD OF 'RELOAD CHECKPOINT'", "" },
            { "DIFFICULTY THRESHOLD FOR IGNORING HOSTILE CREATURES", "" },
            { "DISABLE ACHIEVEMENTS", "" },
            { "DISABLE BLOOD SPLATTERS", "" },
            { "DISABLE BRAIN HIJACKING ON PLAYER-CONTROLLED CHARACTERS", "" },
            { "DISABLE CONFLICT CHECKING WHEN REBINDING CONTROLS", "" },
            { "DISABLE FLOOR TEXTURES", "" },
            { "DISABLE FULLSCREEN COLOR EFFECTS (FOR COLOR BLINDNESS)", "" },
            { "DISABLE FULLSCREEN SCREEN-WARPING EFFECTS", "" },
            { "DISABLE INPUT WARNING", "" },
            { "DISABLE LIMIT ON ZONE BUILD TRIES", "" },
            { "DISABLE MODERN, TILE-BASED GRAPHICAL EFFECTS", "" },
            { "DISABLE MOST TILE-BASED FLASHING EFFECTS", "" },
            { "DISABLE PRELOADING OF SOUNDS", "" },
            { "DISABLE SMOKE EFFECTS", "" },
            { "DISABLE TILE-BASED SCREEN-WARPING EFFECTS", "" },
            { "DISABLE ZONE CACHING", "" },
            { "DISPLAY ABILITY ICONS ON THE SIDEBAR", "" },
            { "DISPLAY ASCII VISUAL EFFECTS", "" },
            { "DISPLAY BITS WITH ALPHANUMERICS INSTEAD OF DOTS (FOR COLOR BLINDNESS)", "" },
            { "DISPLAY COMBAT ANIMATIONS", "" },
            { "DISPLAY CONTENTS OF CURRENT CELL IN A POPUP", "" },
            { "DISPLAY DETAILED WEAPON PENETRATION AND DAMAGE IN WEAPON NAMES", "" },
            { "DISPLAY FLOATING DAMAGE NUMBERS", "" },
            { "DISPLAY LOCATION INSTEAD OF NAME ON THE SIDEBAR", "" },
            { "DISPLAY MODERN VISUAL EFFECTS", "" },
            { "DISPLAY MOUSE-CLICKABLE ZONE TRANSITION ARROWS", "" },
            { "DISPLAY OVERLAY KEYBOARD FOR INPUT ON SUPPORTED DEVICES", "" },
            { "DISPLAY POPUPS WHEN NOTING INFORMATION IN YOUR JOURNAL", "" },
            { "DISPLAY SCANLINES", "" },
            { "DISPLAY VERBOSE LEVEL UP MESSAGES FOR COMPANIONS", "" },
            { "DISPLAY VIGNETTE EFFECT", "" },
            { "DO NOT GENERATE FLOOR TEXTURE OBJECTS", "" },
            { "DOCK BACKGROUND OPACITY", "" },
            { "DOCK MESSAGE LOG && MINIMAP", "" },
            { "DON'T DELETE CLASSIC MODE SAVED GAMES ON DEATH", "" },
            { "DRAW AUDIBILITY FLOOD FILL", "" },
            { "DRAW CELLULAR AUTOMATA WHEN USED IN MAP GENERATION", "" },
            { "DRAW CREATURE PATHFINDING ", "" },
            { "DRAW ELECTRICAL ARC HISTORY FOR LAST FEW ROUNDS", "" },
            { "DRAW NAVIGATION WEIGHT MAPS ON EACH STEP", "" },
            { "DRAW OLFACTION FLOOD FILL", "" },
            { "DRAW POPULATION PLACEMENT HINT MAPS WHEN BUILDING ZONES", "" },
            { "DRAW POPULATION PLACEMENT REGIONS WHEN BUILDING ZONES", "" },
            { "DRAW REACHABILITY MAPS ON ZONE GENERATION", "" },
            { "DRAW SEMANTIC TAG INFO WHEN BUILDING ZONES", "" },
            { "DRAW VISIBILITY FLOOD FILL", "" },
            { "Default", "" },
            { "Default the selection on death prompts in Roleplay mode to 'View final messages' instead of 'Reload checkpoint'", "" },
            { "Dehydrated", "" },
            { "Difficulty threshold for ignoring hostile creatures", "" },
            { "Disable achievements", "" },
            { "Disable blood splatters", "" },
            { "Disable brain hijacking on player-controlled characters", "" },
            { "Disable conflict checking when rebinding controls", "" },
            { "Disable floor textures", "" },
            { "Disable fullscreen color effects (for color blindness)", "" },
            { "Disable fullscreen screen-warping effects", "" },
            { "Disable input warning", "" },
            { "Disable limit on zone build tries", "" },
            { "Disable modern, tile-based graphical effects", "" },
            { "Disable most tile-based flashing effects", "" },
            { "Disable preloading of sounds", "" },
            { "Disable smoke effects", "" },
            { "Disable tile-based screen-warping effects", "" },
            { "Disable zone caching", "" },
            { "Display ASCII visual effects", "" },
            { "Display ability icons on the sidebar", "" },
            { "Display bits with alphanumerics instead of dots (for color blindness)", "" },
            { "Display combat animations", "" },
            { "Display contents of current cell in a popup", "" },
            { "Display detailed weapon penetration and damage in weapon names", "" },
            { "Display floating damage numbers", "" },
            { "Display location instead of name on the sidebar", "" },
            { "Display modern visual effects", "" },
            { "Display mouse-clickable zone transition arrows", "" },
            { "Display overlay keyboard for input on supported devices", "" },
            { "Display popups when noting information in your journal", "" },
            { "Display scanlines", "" },
            { "Display verbose level up messages for companions", "" },
            { "Display vignette effect", "" },
            { "Do not generate floor texture objects", "" },
            { "Dock background opacity", "" },
            { "Dock message log && minimap", "" },
            { "Don't delete Classic mode saved games on death", "" },
            { "Draw audibility flood fill", "" },
            { "Draw cellular automata when used in map generation", "" },
            { "Draw creature pathfinding", "" },
            { "Draw creature pathfinding ", "" },
            { "Draw electrical arc history for last few rounds", "" },
            { "Draw navigation weight maps on each step", "" },
            { "Draw olfaction flood fill", "" },
            { "Draw population placement hint maps when building zones", "" },
            { "Draw population placement regions when building zones", "" },
            { "Draw reachability maps on zone generation", "" },
            { "Draw semantic tag info when building zones", "" },
            { "Draw visibility flood fill", "" },
            { "ENABLE A 'DROP ALL' INTERACTION ON ITEMS IN YOUR INVENTORY", "" },
            { "ENABLE COLOR MENU FOR TEXT INPUT", "" },
            { "ENABLE HARMONY DEBUG OUTPUT", "" },
            { "ENABLE MODERN UI", "" },
            { "ENABLE MODERN UI CHARACTER SHEET", "" },
            { "ENABLE MODS", "" },
            { "ENABLE SAVE AND LOAD", "" },
            { "ENABLE TILE GRAPHICS", "" },
            { "ENABLE UNFINISHED AND UNSUPPORTED CONTENT", "" },
            { "ENABLE WORKAROUND FOR STEAM DECK SHIFT KEY BUG", "" },
            { "EQUIP/UNEQUIP HIGHLIGHTED ITEM WHEN PRESSING RIGHT OR LEFT, RESPECTIVELY, ON THE EQUIPMENT SCREEN", "" },
            { "EXPAND THE EQUIPMENT OR INVENTORY PANE WHEN FOCUSED", "" },
            { "Easy", "" },
            { "Enable Harmony debug output", "" },
            { "Enable a 'drop all' interaction on items in your inventory", "" },
            { "Enable color menu for text input", "" },
            { "Enable modern UI", "" },
            { "Enable modern UI character sheet", "" },
            { "Enable mods", "" },
            { "Enable save and load", "" },
            { "Enable tile graphics", "" },
            { "Enable unfinished and unsupported content", "" },
            { "Enable workaround for Steam Deck shift key bug", "" },
            { "Equip/unequip highlighted item when pressing right or left, respectively, on the Equipment screen", "" },
            { "Expand the equipment or inventory pane when focused", "" },
            { "FIRE CRACKLING SOUNDS", "" },
            { "FLUSH ZONES TO CACHE EARLY (FOR LOW MEMORY ENVIRONMENTS)", "" },
            { "FRAME RATE", "" },
            { "FULLSCREEN", "" },
            { "FULLSCREEN RESOLUTION", "" },
            { "Fire crackling sounds", "" },
            { "Fit", "" },
            { "Flip", "" },
            { "Flush zones to cache early (for low memory environments)", "" },
            { "Frame rate", "" },
            { "Full", "" },
            { "Full Height", "" },
            { "Fullscreen", "" },
            { "Fullscreen resolution", "" },
            { "GAMEPAD BUTTON APPEARANCE", "" },
            { "GARBAGE COLLECT AFTER EACH ZONE FLUSH (FOR LOW MEMORY ENVIRONMENTS)", "" },
            { "GET PROMPTED TO CONFIRM DEATHS", "" },
            { "Gamepad button appearance", "" },
            { "Garbage collect after each zone flush (for low memory environments)", "" },
            { "Get prompted to confirm deaths", "" },
            { "IGNORE ALL EFFECTS THAT RECOLOR YOUR CHARACTER'S GLYPH OTHER THAN HEALTH STATUS", "" },
            { "INDENT BODY PARTS BY ATTACHMENT ON THE EQUIPMENT SCREEN", "" },
            { "INDICATE BIOMES ON THE WORLDMAP", "" },
            { "INDICATE SPECIAL ENCOUNTERS ON THE WORLDMAP", "" },
            { "INTERFACE SOUNDS", "" },
            { "INTERFACE VOLUME", "" },
            { "INTERRUPT HELD MOVEMENT WHEN ENTERING AN UNEXPLORED ZONE", "" },
            { "INTERRUPT HELD MOVEMENT WHEN HOSTILES ARE NEARBY", "" },
            { "Ignore all effects that recolor your character's glyph other than health status", "" },
            { "Impossible", "" },
            { "Indent body parts by attachment on the Equipment screen", "" },
            { "Indicate biomes on the worldmap", "" },
            { "Indicate special encounters on the worldmap", "" },
            { "Interface sounds", "" },
            { "Interface volume", "" },
            { "Interrupt held movement when entering an unexplored zone", "" },
            { "Interrupt held movement when hostiles are nearby", "" },
            { "KBM", "" },
            { "KEEP CAVES OF QUD ACTIVE IN BACKGROUND", "" },
            { "KEY REPEAT DELAY", "" },
            { "KEY REPEAT RATE", "" },
            { "Keep Caves of Qud active in background", "" },
            { "Key repeat delay", "" },
            { "Key repeat rate", "" },
            { "LIMIT THE INPUT BUFFER TO TWO COMMANDS", "" },
            { "Left", "" },
            { "Limit the input buffer to two commands", "" },
            { "MAIN MENU BACKGROUND ART", "" },
            { "MAIN VOLUME", "" },
            { "MAP SHIFT+DIRECTIONS TO MENU PAGINATION BINDS (DOESN'T WORK FOR NUMPAD BINDINGS)", "" },
            { "MAXIMUM AUTOMOVE CELLS/SEC AND AUTOATTACK ACTIONS/SEC", "" },
            { "MESSAGE LOG FONT SIZE (PT)", "" },
            { "MOUSE CURSOR APPEARANCE", "" },
            { "MOVE TUTORIAL TO THE END OF THE GAME MODE LIST", "" },
            { "MUSIC", "" },
            { "MUSIC VOLUME", "" },
            { "Main menu background art", "" },
            { "Main volume", "" },
            { "Map Shift+directions to menu pagination binds (doesn't work for numpad bindings)", "" },
            { "Maximum automove cells/sec and autoattack actions/sec", "" },
            { "Message log font size (pt)", "" },
            { "Modern", "" },
            { "Mouse cursor appearance", "" },
            { "Move tutorial to the end of the game mode list", "" },
            { "Music", "" },
            { "Music volume", "" },
            { "NAVIGATE INVENTORY AND EQUIPMENT PANES WITH LEFT/RIGHT PAGINATION INSTEAD OF MOVEMENT BINDS", "" },
            { "NEARBY OBJECTS LIST: SHOW LIQUID POOLS", "" },
            { "NEARBY OBJECTS LIST: SHOW ONLY CURRENT CELL'S CONTENTS", "" },
            { "NEARBY OBJECTS LIST: SHOW ONLY SHOW TAKEABLE OBJECTS", "" },
            { "NEARBY OBJECTS LIST: SHOW PLANTS", "" },
            { "NUMBER OF ROLLING BACKUP SAVES", "" },
            { "Navigate inventory and equipment panes with left/right pagination instead of movement binds", "" },
            { "Nearby objects list: show liquid pools", "" },
            { "Nearby objects list: show only current cell's contents", "" },
            { "Nearby objects list: show only show takeable objects", "" },
            { "Nearby objects list: show plants", "" },
            { "No Warning", "" },
            { "None", "" },
            { "Number of rolling backup saves", "" },
            { "PERFORM INVENTORY CONSISTENCY CHECKS", "" },
            { "PIXEL PERFECT TILE GRAPHIC SCALE", "" },
            { "PLAY AREA SCALE", "" },
            { "PREGENERATE ZONE NAMES FOR WISH SUPPORT", "" },
            { "PRESSING SHIFT HIDES THE SIDEBAR", "" },
            { "PROMPT BEFORE AUTOWALKING TO STAIRS", "" },
            { "PROMPT BEFORE DRINKING AND MOVING INTO CERTAIN DANGEROUS LIQUIDS", "" },
            { "PROMPT BEFORE MOVING TO THE WORLD MAP", "" },
            { "PROMPT BEFORE SWIMMING", "" },
            { "PROMPT LIST OF ITEMS WHEN GETTING FROM THE GROUND, EVEN IF THERE'S ONLY ONE", "" },
            { "PS", "" },
            { "PS Filled", "" },
            { "Parched", "" },
            { "Perform inventory consistency checks", "" },
            { "Pixel Perfect", "" },
            { "Pixel perfect tile graphic scale", "" },
            { "Play area scale", "" },
            { "Pregenerate zone names for wish support", "" },
            { "Pressing shift hides the sidebar", "" },
            { "Prompt before autowalking to stairs", "" },
            { "Prompt before drinking and moving into certain dangerous liquids", "" },
            { "Prompt before moving to the world map", "" },
            { "Prompt before swimming", "" },
            { "Prompt list of items when getting from the ground, even if there's only one", "" },
            { "Quenched", "" },
            { "RANGE THRESHOLD FOR IGNORING HOSTILE CREATURES", "" },
            { "Range threshold for ignoring hostile creatures", "" },
            { "Right", "" },
            { "SEARCH CONTAINERS WHILE AUTOEXPLORING", "" },
            { "SEND ANONYMOUS GAMEPLAY STATISTICS", "" },
            { "SHOW ABILITY-ON-COOLDOWN PROMPTS AS MESSAGE LOG ENTRIES INSTEAD OF POPUPS", "" },
            { "SHOW ADVANCED OPTIONS", "" },
            { "SHOW ATTITUDE INFO ON OBJECTS", "" },
            { "SHOW COLLECTOR'S SEALS ON THE MAIN MENU", "" },
            { "SHOW DAMAGE PENETRATION DEBUG TEXT", "" },
            { "SHOW DEBUG INFO ON OBJECTS", "" },
            { "SHOW DEBUG TEXT FOR STAT SHIFTS", "" },
            { "SHOW ENCOUNTER CHANCE DEBUG CHANCE", "" },
            { "SHOW ERROR POPUPS", "" },
            { "SHOW LOST CHANCE DEBUG TEXT", "" },
            { "SHOW MINIMAP", "" },
            { "SHOW NEARBY OBJECTS LIST", "" },
            { "SHOW NUMBER OF ITEMS IN EACH INVENTORY CATEGORY", "" },
            { "SHOW POPUPS WHEN YOU DISMEMBER OR DECAPITATE SOMEONE", "" },
            { "SHOW QUICKSTART OPTION DURING CHARACTER CREATION", "" },
            { "SHOW REPUTATION WITH A CREATURE'S FACTIONS WHEN LOOKING AT THEM", "" },
            { "SHOW SAVING THROW DEBUG TEXT", "" },
            { "SHOW SCAVENGED ITEMS AS MESSAGE LOG ENTRIES INSTEAD OF POPUPS", "" },
            { "SHOW THE FULL ZONE ID DURING ZONE CREATION", "" },
            { "SHOW TRAVEL SPEED DEBUG TEXT", "" },
            { "SHOW XML CONVERSATION AND NODE NAMES DURING CONVERSATION", "" },
            { "SOUND EFFECTS", "" },
            { "SOUND EFFECTS VOLUME", "" },
            { "STRIP COLOR FORMATTING FROM UI TEXT", "" },
            { "Search containers while autoexploring", "" },
            { "Send anonymous gameplay statistics", "" },
            { "Show XML conversation and node names during conversation", "" },
            { "Show ability-on-cooldown prompts as message log entries instead of popups", "" },
            { "Show advanced options", "" },
            { "Show attitude info on objects", "" },
            { "Show collector's seals on the main menu", "" },
            { "Show damage penetration debug text", "" },
            { "Show debug info on objects", "" },
            { "Show debug text for stat shifts", "" },
            { "Show encounter chance debug chance", "" },
            { "Show error popups", "" },
            { "Show lost chance debug text", "" },
            { "Show minimap", "" },
            { "Show nearby objects list", "" },
            { "Show number of items in each inventory category", "" },
            { "Show popups when you dismember or decapitate someone", "" },
            { "Show quickstart option during character creation", "" },
            { "Show reputation with a creature's factions when looking at them", "" },
            { "Show saving throw debug text", "" },
            { "Show scavenged items as message log entries instead of popups", "" },
            { "Show the full zone ID during zone creation", "" },
            { "Show travel speed debug text", "" },
            { "Sound effects", "" },
            { "Sound effects volume", "" },
            { "Standard", "" },
            { "Strip color formatting from UI text", "" },
            { "System", "" },
            { "TAKE CORPSES WHEN USING THE 'TAKE ALL' COMMAND", "" },
            { "THIRST THRESHOLD FOR AUTOMATIC DRINKING", "" },
            { "THRESHOLD FOR LOW HITPOINT WARNING", "" },
            { "THROTTLE ANIMATIONS (FOR LOW CPU ENVIRONMENTS)", "" },
            { "TOOLTIP DELAY (MS)", "" },
            { "Take corpses when using the 'take all' command", "" },
            { "Thirst threshold for automatic drinking", "" },
            { "Thirsty", "" },
            { "Threshold for low hitpoint warning", "" },
            { "Throttle animations (for low CPU environments)", "" },
            { "Tooltip delay (ms)", "" },
            { "Tough", "" },
            { "Tumescent", "" },
            { "UI SCALE", "" },
            { "UI scale", "" },
            { "USE TEXT AUTOACT INTERRUPT INDICATOR INSTEAD OF FLASHING RED BOX", "" },
            { "Unlimited", "" },
            { "Unset", "" },
            { "Use text autoact interrupt indicator instead of flashing red box", "" },
            { "VSync", "" },
            { "Very Tough", "" },
            { "WAIT FOR KEYPRESS WHEN DRAWING PATHFINDING", "" },
            { "WHEN ZOOMED OUT TO MAX ZOOM, REMOVE THE UI FRAME FROM THE MAIN GAMEPLAY SCREEN", "" },
            { "WRITE COMPILED MOD ASSEMBLIES TO DISK", "" },
            { "WRITE PLAYED SOUND FILE NAMES TO MESSAGE LOG", "" },
            { "Wait for keypress when drawing pathfinding", "" },
            { "When you load a save from the main menu rolling backups of loaded saves will be maintained in your data folder (<...>/CavesOfQud/Local/Session) up to this number.", "" },
            { "When zoomed out to max zoom, remove the UI frame from the main gameplay screen", "" },
            { "Write compiled mod assemblies to disk", "" },
            { "Write played sound file names to message log", "" },
            { "XBox", "" },
            { "XBox Filled", "" },
            { "ZOOM SENSITIVITY", "" },
            { "Zoom sensitivity", "" },
            { "auto", "" },
            { "auto x1.25", "" },
            { "auto x1.5", "" },
            { "ì", "" }

        };
    }
}

