using System;
using System.Reflection;
using System.Linq;
using System.Text;

class Program
{
    static void Main(string[] args)
    {
        string dllPath = "../Assets/harmony_source/0Harmony_BaseGame.dll";
        try
        {
            Assembly asm = Assembly.LoadFrom(dllPath);
            Console.WriteLine($"// Decompiled API of: {asm.FullName}");
            Console.WriteLine($"// Location: {dllPath}");
            Console.WriteLine("// Generated by QudKR Analyzer");
            Console.WriteLine();

            foreach (Type type in asm.GetTypes().OrderBy(t => t.FullName))
            {
                if (!type.IsPublic) continue;

                Console.WriteLine($"public class {type.FullName}");
                Console.WriteLine("{");

                foreach (var method in type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly))
                {
                    string staticPrefix = method.IsStatic ? "static " : "";
                    string returnType = method.ReturnType.Name;
                    string parameters = string.Join(", ", method.GetParameters().Select(p => $"{p.ParameterType.Name} {p.Name}"));
                    
                    Console.WriteLine($"    public {staticPrefix}{returnType} {method.Name}({parameters});");
                }

                Console.WriteLine("}");
                Console.WriteLine();
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"// Error loading assembly: {ex.Message}");
        }
    }
}
